artifacts_root: artifacts

data ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/dhruvj94/end-to-end-machine-learning-project-with-MLfllow/raw/refs/heads/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion