artifacts_root: artifacts


data ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/dhruvj94/end-to-end-machine-learning-project-with-MLfllow/raw/refs/heads/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  STATUS_FILE_2: artifacts/data_validation/status_2.txt